prgrms-web-devcourse-final-project/WEB1_1_Bongdari_BE

- src/main/java/com/somemore/recruitboard/domain/RecruitBoard.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
- src/test/java/com/somemore/recruitboard/domain/RecruitBoardTest.java
- src/test/java/com/somemore/recruitboard/service/command/CreateRecruitBoardServiceTest.java
resolved : 
- #18
- 봉사 모집글 생성 기능 수정
- 기존) 봉사 시작 일시, 봉사 시간(시간, 분) 입력
- 변경) 봉사 시작 일시, 봉사 종료 일시 입력
- `RecruitBoard`에 대한 테스트가 적절한지 봐주시면 감사하겠습니다.
> Feature/18 봉사 모집글 생성 기능 수정

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- 과도한 도커 이미지 생성으로 인해 이미지 빌드및 push 과정을 CD.yml workflow를 만들어 분리하였습니다
resolved : #31  
과도한 도커 이미지 생성 방지를 위해 이미지 업로드 과정을 CD.yml을 만들어 분리시켰습니다.
- CD.yml workflow 생성
- 도커 이미지 업로드 과정을 CD.yml로 분리
> CICD/31 도커 이미지 업로드 과정 분리

- src/main/java/com/somemore/center/dto/response/CenterForCommunityResponseDto.java
- src/main/java/com/somemore/center/repository/CenterJpaRepository.java
- src/main/java/com/somemore/center/repository/CenterRepository.java
- src/main/java/com/somemore/center/repository/CenterRepositoryImpl.java
- src/main/java/com/somemore/center/service/query/CenterQueryService.java
- src/main/java/com/somemore/center/usecase/query/CenterQueryUseCase.java
- src/main/java/com/somemore/community/dto/response/CommunityBoardGetDetailResponseDto.java
- src/main/java/com/somemore/community/dto/response/CommunityBoardGetResponseDto.java
- src/main/java/com/somemore/community/dto/response/WriterDetailDto.java
- src/main/java/com/somemore/community/repository/CommunityBoardJpaRepository.java
- src/main/java/com/somemore/community/repository/CommunityBoardRepository.java
- src/main/java/com/somemore/community/repository/CommunityRepositoryImpl.java
- src/main/java/com/somemore/community/service/query/CommunityBoardQueryService.java
- src/main/java/com/somemore/community/usecase/query/CommunityBoardQueryUseCase.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
- src/main/java/com/somemore/volunteer/dto/response/VolunteerForCommunityResponseDto.java
- src/main/java/com/somemore/volunteer/repository/VolunteerJpaRepository.java
- src/main/java/com/somemore/volunteer/repository/VolunteerRepositoryImpl.java
- src/main/java/com/somemore/volunteer/service/query/FindVolunteerIdService.java
- src/main/java/com/somemore/volunteer/usecase/query/FindVolunteerIdUseCase.java
- src/test/java/com/somemore/center/repository/CenterRepositoryTest.java
- src/test/java/com/somemore/center/service/query/CenterQueryServiceTest.java
- src/test/java/com/somemore/community/repository/CommunityRepositoryTest.java
- src/test/java/com/somemore/community/service/query/CommunityBoardQueryServiceTest.java
- src/test/java/com/somemore/volunteer/repository/VolunteerRepositoryTest.java
- src/test/java/com/somemore/volunteer/service/query/FindVolunteerIdServiceTest.java
resolved : 
- #19 
커뮤니티 게시글 조회 기능
- 커뮤니티 게시글 전체 리스트 조회 기능
- 커뮤니티 게시글 리스트 작성자별 조회 기능
- 커뮤니티 게시글 상세 조회 기능
- center name 조회 기능
- center 커뮤니티 게시글에 포함될 상세 정보 조회 기능
- volunteer nickname 조회 기능
- volunteer 커뮤니티 게시글에 포함될 상세 정보 조회 기능
작성자 정보 조회 과정에서 center와 volunteer responseDto를 WriterDetailDto interface를 implements 받는 구조로 구현하였는데 WriterDetailDto 이름이나 디렉토리 위치가 어떤지 리뷰 남겨주시면 감사하겠습니다!
> Feature/19 커뮤니티 게시글 조회 기능

- src/main/java/com/somemore/community/domain/CommunityBoard.java
- src/main/java/com/somemore/community/service/command/DeleteCommunityBoardService.java
- src/main/java/com/somemore/community/usecase/command/DeleteCommunityBoardUseCase.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
- src/test/java/com/somemore/community/service/command/DeleteCommunityBoardServiceTest.java
- src/test/java/com/somemore/community/service/query/CommunityBoardQueryServiceTest.java
resolved : 
- #47 
커뮤니티 게시글 삭제 기능
- 커뮤니티 게시글 삭제 기능
- 이미 삭제된 게시글 삭제 시 exception 메시지
> Feature/47 커뮤니티 게시글 삭제 기능 

- .github/workflows/CD.yml
- .github/workflows/CI.yml
> CICD/ 환경 변수 추가

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- build.gradle
- src/main/java/com/somemore/global/configure/S3Config.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
- src/main/java/com/somemore/global/exception/ImageUploadException.java
- src/main/java/com/somemore/global/handler/GlobalExceptionHandler.java
- src/main/java/com/somemore/imageupload/dto/ImageUploadRequestDto.java
- src/main/java/com/somemore/imageupload/service/ImageUploadService.java
- src/main/java/com/somemore/imageupload/usecase/ImageUploadUseCase.java
- src/main/java/com/somemore/imageupload/util/ImageUploadUtils.java
- src/main/java/com/somemore/imageupload/validator/DefaultImageUploadValidator.java
- src/main/java/com/somemore/imageupload/validator/ImageUploadValidator.java
- src/main/resources/application.yml
- src/test/java/com/somemore/imageupload/service/ImageUploadServiceTest.java
- src/test/java/com/somemore/imageupload/util/ImageUploadUtilsTest.java
- src/test/java/com/somemore/imageupload/validator/DefaultImageUploadValidatorTest.java
- src/test/resources/application-test.yml
resolved : #36   
s3에 이미지를 업로드 하는 기능 구현입니다.
- aws s3 연동을 위한 의존성 추가
- 환경변수 추가
- S3 연결을 위한 config 클래스 구현
- 서비스 레이어에 이미지 업로드 기능 구현
- 업로드 실패 예외와 예외 메세지 추
- test.yml에 테스트에 필요한 환경변수 추가
- 테스트 코드 작성및 검증 완료
> Feature/36 s3 이미지 업로드 기능 구현

- src/main/java/com/somemore/community/domain/CommunityComment.java
- src/main/java/com/somemore/community/service/comment/DeleteCommunityCommentService.java
- src/main/java/com/somemore/community/usecase/comment/DeleteCommunityCommentUseCase.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
- src/test/java/com/somemore/community/service/comment/DeleteCommunityCommentServiceTest.java
resolved :
- #68 
커뮤니티 댓글 삭제 기능
- 커뮤니티 댓글 삭제
- 작성자가 아닐 경우 예외 처리
> Feature/68 커뮤니티 댓글 삭제 기능

- src/main/java/com/somemore/center/controller/CenterQueryApiController.java
- src/main/java/com/somemore/center/domain/Center.java
- src/main/java/com/somemore/center/dto/response/CenterProfileResponseDto.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
- src/test/java/com/somemore/ControllerTestSupport.java
- src/test/java/com/somemore/center/controller/CenterQueryApiControllerTest.java
resolved : #69  
기관 프로필 조회의 컨트롤러 구현과 테스트 코드 입니다.
- 기관 프로필 조회 컨트롤러 구현
- center 엔티티의 PK에 columnDefinition = "BINARY(16)" 명시
presentation 레이어 테스트를 작성하는데 많이 어색한 느낌이었습니다.
테스트 작성이 잘 되었는지 여쭤보고 싶어요
> Feature/69 기관 프로필 조회 컨트롤러 구현

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- 기본 이미지 주소를 저장한 환경변수 값추가
기본 이미지 url 설정을 위한 환경변수 추가
> cicd: workflow 환경변수 추가

- src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
- src/main/java/com/somemore/auth/util/DevAccountSetUpConfig.java
- src/main/java/com/somemore/center/repository/CenterJpaRepository.java
- src/main/java/com/somemore/global/configure/SwaggerConfig.java
- src/main/resources/application.yml
- src/test/resources/application-test.yml
resolved : 
- #89 
- 스웨거 API 테스트를 위한 봉사자 / 기관 토큰 발급
- 사용 방법
-  https://www.notion.so/prgrms/Swagger-API-765b05b3e31e460c99f976bf296c1036?pvs=4
> Feature/89 스웨거 API 테스트를 위한 봉사자 / 기관 토큰 발급

- src/main/java/com/somemore/imageupload/converter/MultipartJackson2HttpMessageConverter.java
- src/main/java/com/somemore/imageupload/service/ImageUploadService.java
- src/main/java/com/somemore/imageupload/validator/DefaultImageUploadValidator.java
- src/main/java/com/somemore/imageupload/validator/ImageUploadValidator.java
- src/main/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiController.java
- src/main/java/com/somemore/recruitboard/controller/RecruitBoardQueryApiController.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardStatusUpdateRequestDto.java
- src/main/resources/application.yml
- src/test/java/com/somemore/CustomSecurityContextFactory.java
- src/test/java/com/somemore/WithMockCustomUser.java
- src/test/java/com/somemore/imageupload/service/ImageUploadServiceTest.java
- src/test/java/com/somemore/imageupload/validator/DefaultImageUploadValidatorTest.java
- src/test/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
- src/test/java/com/somemore/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
- src/test/resources/application-test.yml
resolved:
- #81  
- 봉사 모집글 생성 기능 컨트롤러 작업
- 봉사 모집글 수정 기능 컨트롤러 작업
- 봉사 모집글 삭제 기능 컨트롤러 작업
- 스웨거 테스트 완료
> Feature/81 봉사 모집글 생성, 수정, 삭제 컨트롤러 생성

- build.gradle
- src/main/java/com/somemore/global/handler/GlobalExceptionHandler.java
- src/main/java/com/somemore/volunteer/controller/VolunteerProfileCommandController.java
- src/main/java/com/somemore/volunteer/controller/VolunteerProfileQueryController.java
- src/main/java/com/somemore/volunteer/domain/Volunteer.java
- src/main/java/com/somemore/volunteer/dto/request/VolunteerProfileUpdateRequestDto.java
- src/main/java/com/somemore/volunteer/dto/response/VolunteerProfileResponseDto.java
- src/main/java/com/somemore/volunteer/service/UpdateVolunteerProfileService.java
- src/main/java/com/somemore/volunteer/service/VolunteerQueryService.java
- src/main/java/com/somemore/volunteer/usecase/UpdateVolunteerProfileUseCase.java
- src/main/java/com/somemore/volunteer/usecase/VolunteerQueryUseCase.java
- src/test/java/com/somemore/volunteer/controller/VolunteerProfileCommandControllerTest.java
- src/test/java/com/somemore/volunteer/service/UpdateVolunteerProfileServiceTest.java
- src/test/java/com/somemore/volunteer/service/VolunteerQueryServiceTest.java
**resolved**:  
- #97 
---
- 봉사자 프로필 수정 기능을 추가하였습니다.
- 사용자는 닉네임, 소개글, 프로필 이미지를 수정할 수 있습니다.
- RequestDto에 대한 유효성 검사가 추가되었고, 관련 테스트도 구현하였습니다.
---
1. **봉사자 업데이트 (domain, usecase-service, controller)**
2. `build(gradle): validation 의존성 추가`
- 유효성 검사를 위해 `spring-boot-starter-validation`을 추가하였습니다.
3. `feat(GlobalExceptionHandler): 유효성 예외를 전역 예외 핸들러로 처리`
- `MethodArgumentNotValidException` 발생 시 사용자에게 명확한 오류 메시지를 제공하도록 `GlobalExceptionHandler`를 수정하였습니다. 일관성을 위해서 기존의 상속 구조를 포기했습니다.
4. Volunteer 패키지 내의 명확하지 않은 클래스들 Rename.
---
1. 닉네임 10자, 소개 100자가 적절하지 않다면 알려주세요!
> Feature/97 봉사자 프로필 수정

- src/main/java/com/somemore/auth/annotation/CurrentUser.java
- src/main/java/com/somemore/center/controller/CenterSignController.java
- src/main/java/com/somemore/center/controller/PreferItemCommandApiController.java
- src/main/java/com/somemore/center/dto/request/CenterSignRequestDto.java
- src/main/java/com/somemore/global/common/response/ApiResponse.java
- src/main/java/com/somemore/interestcenter/controller/InterestCenterQueryApiController.java
- src/main/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiController.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
- src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardDetailResponseDto.java
- src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardResponseDto.java
- src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithCenterResponseDto.java
- src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithLocationResponseDto.java
- src/main/java/com/somemore/review/controller/ReviewCommandApiController.java
- src/main/java/com/somemore/review/dto/response/ReviewResponseDto.java
- src/main/java/com/somemore/review/dto/response/ReviewWithNicknameResponseDto.java
- src/main/java/com/somemore/volunteer/controller/VolunteerProfileCommandController.java
- src/main/java/com/somemore/volunteer/controller/VolunteerProfileQueryController.java
- src/test/java/com/somemore/CustomSecurityContextFactory.java
resolved : 
- #122 
- 인증된 사용자의 ID(UUID)를 스트링이 아닌 UUID로 가져오도록 변경
- 스웨거 날짜 example 이 제대로 나오지 않는 문제 해결
- ApiResponse 스웨거 적용
- 기관 로그인 스웨거에 문서화
- 이제 @CurrentUser 어노테이션 사용하시면 UUID 형태로 id 담아오실수 있습니다.
- <img width="505" alt="image" src="https://github.com/user-attachments/assets/5748b929-136c-4e55-9868-6b453c4c0188">
- 응답또는 요구 DTO 필드에 날짜가 있는 경우 type = "string"을 적어주시면 스웨거 문서에 제대로 값이 출력됩니다.
- <img width="821" alt="image" src="https://github.com/user-attachments/assets/cd9b4bb2-0a39-4037-a0f0-5f61b8594e97">
- ApiReponse 스웨거 적용(없는것 보단 나은것 같아서 적용했습니다.)
- <img width="865" alt="image" src="https://github.com/user-attachments/assets/6de09cca-3b3f-4973-9f72-a96400c06e2f">
> Refactor/122 인증 유저 어노테이션 및 스웨거 관련 수정

- src/main/java/com/somemore/community/controller/CommunityBoardCommandApiController.java
- src/main/java/com/somemore/community/controller/CommunityBoardQueryApiController.java
- src/main/java/com/somemore/community/controller/CommunityCommentCommandApiController.java
- src/main/java/com/somemore/community/controller/CommunityCommentQueryApiController.java
- src/main/java/com/somemore/community/dto/request/CommunityCommentCreateRequestDto.java
- src/main/java/com/somemore/community/dto/response/CommunityBoardDetailResponseDto.java
- src/main/java/com/somemore/community/service/comment/CreateCommunityCommentService.java
- src/main/java/com/somemore/community/service/comment/DeleteCommunityCommentService.java
- src/main/java/com/somemore/community/service/comment/UpdateCommunityCommentService.java
- src/main/java/com/somemore/community/usecase/comment/CreateCommunityCommentUseCase.java
- src/main/java/com/somemore/community/usecase/comment/DeleteCommunityCommentUseCase.java
- src/main/java/com/somemore/community/usecase/comment/UpdateCommunityCommentUseCase.java
- src/test/java/com/somemore/community/controller/CommunityBoardCommandApiControllerTest.java
- src/test/java/com/somemore/community/controller/CommunityBoardQueryApiControllerTest.java
- src/test/java/com/somemore/community/controller/CommunityCommentCommandApiControllerTest.java
- src/test/java/com/somemore/community/controller/CommunityCommentQueryApiControllerTest.java
- src/test/java/com/somemore/community/service/comment/CommunityCommentQueryServiceTest.java
- src/test/java/com/somemore/community/service/comment/CreateCommunityCommentServiceTest.java
- src/test/java/com/somemore/community/service/comment/DeleteCommunityCommentServiceTest.java
- src/test/java/com/somemore/community/service/comment/UpdateCommunityCommentServiceTest.java
- resolved : #120 
- 커뮤니티 게시글 CRUD 컨트롤러 
- 커뮤니티 댓글 CRUD 컨트롤러
- 게시글, 댓글 컨트롤러 테스트 
컨트롤러 테스트 어렵네요..
> Feature/120 커뮤니티 게시글, 댓글 CRUD 엔드포인트 생성

- src/main/java/com/somemore/note/controller/NoteCommandApiController.java
- src/main/java/com/somemore/note/dto/SendNoteToVolunteerRequestDto.java
- src/main/java/com/somemore/note/service/SendNoteToCenterService.java
- src/main/java/com/somemore/note/service/SendNoteToVolunteerService.java
- src/main/java/com/somemore/note/usecase/SendNoteToVolunteerUseCase.java
- src/main/java/com/somemore/volunteer/repository/VolunteerJpaRepository.java
- src/main/java/com/somemore/volunteer/repository/VolunteerRepository.java
- src/main/java/com/somemore/volunteer/repository/VolunteerRepositoryImpl.java
- src/main/java/com/somemore/volunteer/service/VolunteerQueryService.java
- src/main/java/com/somemore/volunteer/usecase/VolunteerQueryUseCase.java
- src/test/java/com/somemore/note/controller/NoteCommandApiControllerTest.java
- src/test/java/com/somemore/note/service/SendNoteToVolunteerServiceTest.java
- src/test/java/com/somemore/volunteer/repository/VolunteerRepositoryTest.java
- src/test/java/com/somemore/volunteer/service/VolunteerQueryServiceTest.java
- #155  
기관이 봉사자에게 쪽지를 보내는 기능 구현입니다.
- 존재하는 봉사자인지 검증하기 위한 봉사자 exists 메서드 구현
- Note 서비스 레이어에 유스케이스 생성및 메서드 구현
- 컨트롤러 구현
- 일부 클래스의 style 수정
봉사자 도메인에 검증 메서드를 구현했습니다.
저의 메인 도메인이 아니라 컨벤션을 어겼을수도 있으니 잘 봐주시면 감사하겠습니다
> Feature/155 기관 to 봉사자 쪽지 송신 기능 구현

- src/main/java/com/somemore/global/common/response/ApiResponse.java
- src/main/java/com/somemore/volunteerapply/controller/VolunteerApplyQueryApiController.java
resolved :
- #168 
봉사자 지원 조회 기능 수정
지원 내역이 없는 경우 (기존)
- 400 에러
지원 내역이 없는 경우 (변경 후)
-
> Refactor/168 봉사자 지원 조회 기능 수정

- src/main/java/com/somemore/auth/controller/UserInfoQueryController.java
- src/main/java/com/somemore/auth/dto/UserInfoResponseDto.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
resolved : 
- #175 
Header의 Authorization 값에 담긴 AccessToken으로부터 USER_ID와 ROLE을 발급해야 합니다.  
Cookie의 AccessToken이 HttpOnly로 관리되기를 원했기 때문에 JavaScript로 이를 직접 다룰 수 없어, 이를 처리하기 위한 별도의 컨트롤러를 제공해야 했습니다.
- AccessToken으로 만들어진 SecurityContextHolder의 Authentication으로부터 USER_ID와 ROLE을 조회하도록 구현했습니다.
- 어노테이션을 활용해 USER_ROLE을 직접 얻는 방법을 찾지 못한 점이 아쉬웠습니다.  
그래서 SecurityContextHolder에서 Authentication 객체를 가져오는 방식을 사용했습니다.  
- Auth 패키지에 별도의 컨트롤러를 추가했습니다.  
이는 기관과 봉사자 모두를 조회해야 했고, 단일 요청으로 응답을 제공할 필요가 있었기 때문입니다.
> feat/175: AccessToken으로 만들어진 SCH의 Authentication으로부터 userId와 role 조회

- src/main/java/com/somemore/auth/controller/UserInfoQueryController.java
- src/main/java/com/somemore/auth/cookie/CookieService.java
- src/main/java/com/somemore/auth/dto/UserInfoResponseDto.java
- src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
resolved : 
- #178 
AccessToken을 쿠키에 설정해 줄 때, httpOnly로 설정되어 프론트에서 이를 헤더에 담을 수만 있고 Prefix를 설정할 수 없습니다.
Bearer 키워드(공백 유의)가 문제가 되는데 이를 JwtFilter에서 핸들링하겠습니다.
- Bearer 키워드 유무에 따른 토큰 핸들링
- 쿠키에는 `Bearer ` 키워드가 설정될 수 없습니다. 띄어쓰기가 있는 것이 쿠키 정책에 올바르지 않아서 인코딩이 필요했고, 이를 해결하기 위해서 prefix 조건문을 추가했습니다.
- 기존 로직에도, 클라이언트 변경 요청에도 알맞은 결과를 반환합니다.
> Fix/178 AccessToken의 Bearer 키워드 문제 해결

- src/main/java/com/somemore/recruitboard/controller/RecruitBoardQueryApiController.java
- src/main/java/com/somemore/recruitboard/dto/condition/RecruitBoardNearByCondition.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
- src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
- src/test/java/com/somemore/common/fixture/LocalDateTimeFixture.java
resolved : 
- #180 
위치 기반 조회시 모집중이 아닌 데이터도 조회되는 문제 해결
> [BUG] 위치 기반 조회시 모집중이 아닌 데이터도 조회되는 문제 해결

- src/main/java/com/somemore/auth/jwt/domain/EncodedToken.java
- src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
resolved : 
- #182 
쿠키에서 accessToken을 추출할 수 있습니다.
- 쿠키와 헤더 모두에서 토큰을 추출할 수 있음.
- 쿠키에서 토큰을 초기화하지 못하면 헤더에서 토큰을 찾음.
- 헤더에서 토큰을 찾는 이유는 스웨거, 디버깅.
- accessToken 리팩토링.
- 쿠키 NPE 예방.
accessToken 초기화 흐름에 집중해 주세요!
> feat 182/ cookie의 accessToken 추출

- src/main/java/com/somemore/auth/jwt/domain/EncodedToken.java
- src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
- src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
resolved : 
- #186 
- JwtAuthFilter에서 토큰이 없으면 SCH에 AUTH를 설정하지 않고 스킵.
- JwtAuthFilter에서 토큰이 없으면 SCH에 AUTH를 설정하지 않고 스킵.
JWT 예외가 발생하는 이유는 토큰이 없거나 올바르지 않은 값이기 때문입니다.
> fix/ shouldNotFilter 수정

- src/main/java/com/somemore/note/domain/Note.java
- src/main/java/com/somemore/note/repository/NoteRepository.java
- src/main/java/com/somemore/note/repository/NoteRepositoryImpl.java
- src/main/java/com/somemore/note/service/NoteMarkAsReadService.java
- src/main/java/com/somemore/note/service/NoteQueryService.java
- src/main/java/com/somemore/note/usecase/NoteMarkAsReadUseCase.java
- src/test/java/com/somemore/note/service/NoteMarkAsReadServiceTest.java
- #201  
쪽지 상세조회시 읽음처리 기능 추가
- Note 엔티티에 isRead 업데이트 기능 구현
- 기존 쪽지 상세조회 로직에 isRead 업데이트 기능 추가
> Refactor/201 쪽지 상세조회시 읽음처리 기능 추가

- src/main/java/com/somemore/facade/event/VolunteerReviewRequestEvent.java
- src/main/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeService.java
- src/main/java/com/somemore/global/common/event/ServerEvent.java
- src/main/java/com/somemore/notification/converter/MessageConverter.java
- src/main/java/com/somemore/notification/domain/NotificationSubType.java
- src/main/java/com/somemore/notification/handler/NotificationHandlerImpl.java
- src/main/java/com/somemore/volunteerapply/event/VolunteerApplyStatusChangeEvent.java
- src/main/java/com/somemore/volunteerapply/service/ApproveVolunteerApplyService.java
- src/test/java/com/somemore/notification/converter/MessageConverterTest.java
- src/test/java/com/somemore/notification/handler/NotificationHandlerTest.java
- src/test/java/com/somemore/notification/service/NotificationCommandServiceTest.java
- src/test/java/com/somemore/notification/service/NotificationQueryServiceTest.java
resolved : 
- #189 
봉사 정산이 완료된 후, 유저가 후기를 작성할 수 있는 상태가 되면 봉사 후기 요청 이벤트가 발생합니다.
이 이벤트는 Redis Pub/Sub과 SSE를 통해 클라이언트에게 전달되며, 전체 흐름은 다음과 같습니다:
1. 이벤트 발행 (Pub)
- VolunteerReviewRequestEvent를 직렬화하여 Redis의 Pub 채널(Notification topic)로 발행. 
2. 이벤트 수신 (Sub)
- Redis Sub 채널(Notification topic)에서 수신된 메시지를 VolunteerReviewRequestEvent 타입으로 역직렬화.
- VolunteerReviewRequestEvent 타입을 Notification 으로 컨버팅.(서브타입이 **volunteerReviewRequest**로 분류됨.)
3. SSE를 통한 알림 전송
- 서브타입에 따라 생성된 알림을 DB에 저장하고, receiverId 기준으로 SSE를 통해 클라이언트에 전달.
- 이벤트 pub/sub
- 알림 sse
> Feature/189 봉사 후기 요청 이벤트, 알림

- src/main/java/com/somemore/recruitboard/domain/RecruitBoard.java
- src/main/java/com/somemore/recruitboard/domain/RecruitmentInfo.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
- src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
- src/test/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
- src/test/java/com/somemore/recruitboard/domain/RecruitmentInfoTest.java
- src/test/java/com/somemore/recruitboard/service/command/UpdateRecruitBoardServiceTest.java
resolved : 
- #206 
봉사활동 모집글 수정 기능 수정
모집글 수정시 지역 필드 추가
- 프론트 측 요청
> Refactor/206 봉사활동 모집글 수정 기능 수정

- src/main/java/com/somemore/community/event/CommentAddedEvent.java
- src/main/java/com/somemore/community/service/comment/CreateCommunityCommentService.java
- src/main/java/com/somemore/global/common/event/ServerEvent.java
- src/main/java/com/somemore/notification/converter/MessageConverter.java
- src/main/java/com/somemore/notification/domain/NotificationSubType.java
- src/main/java/com/somemore/notification/dto/NotificationResponseDto.java
resolved : 
- #204 
댓글 및 대댓글 작성 시 알림 기능을 추가했습니다.
1. 댓글 작성 시
- 커뮤니티 글 작성자에게 알림이 전송됩니다.
2. 대댓글 작성 시
- 부모 댓글 작성자에게 알림이 전송됩니다.
3. 전체 흐름
- 댓글/대댓글 작성 시, Redis로 이벤트를 발행.
- 이벤트를 구독하여 알림을 생성 및 저장.
- 알림은 SSE를 통해 클라이언트로 실시간 전송.
프론트 요청으로 알림 아이디를 추가했습니다. (읽음 처리할 때 필요)
> Feature/204 댓글 알림

- src/main/java/com/somemore/notification/converter/MessageConverter.java
- src/main/java/com/somemore/notification/domain/NotificationSubType.java
- src/main/java/com/somemore/volunteerapply/event/VolunteerApplyEvent.java
- src/main/java/com/somemore/volunteerapply/service/ApplyVolunteerApplyService.java
resolved : 
- #217 
봉사 신청 알림 추가
봉사 신청 이벤트 발행
봉사 신청 알림 처리
> Feature/217 봉사 신청 알림

- src/main/java/com/somemore/interestcenter/controller/InterestCenterCommandApiController.java
- src/main/java/com/somemore/interestcenter/dto/request/RegisterInterestCenterRequestDto.java
- src/main/java/com/somemore/interestcenter/repository/InterestCenterRepository.java
- src/main/java/com/somemore/interestcenter/repository/InterestCenterRepositoryImpl.java
- src/main/java/com/somemore/interestcenter/service/CancelInterestCenterService.java
- src/main/java/com/somemore/interestcenter/service/RegisterInterestCenterService.java
- src/main/java/com/somemore/interestcenter/usecase/CancelInterestCenterUseCase.java
- src/main/java/com/somemore/interestcenter/usecase/RegisterInterestCenterUseCase.java
- src/test/java/com/somemore/interestcenter/controller/InterestCenterCommandApiControllerTest.java
- src/test/java/com/somemore/interestcenter/repository/InterestCenterRepositoryImplTest.java
- src/test/java/com/somemore/interestcenter/service/CancelInterestCenterServiceTest.java
- src/test/java/com/somemore/interestcenter/service/RegisterInterestCenterServiceTest.java
resolved :
- #228 
관심 기관 삭제 기능 변경
> [REFACTOR] 관심 기관 삭제 기능 변경

- src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
resolved : 
- #243
모집글 레포지토리 리팩토링
> [REFACTOR] 모집글 QueryDsl

- src/main/java/com/somemore/community/controller/CommunityBoardQueryApiController.java
- src/main/java/com/somemore/community/repository/board/CommunityBoardRepository.java
- src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
- src/main/java/com/somemore/community/service/board/CommunityBoardQueryService.java
- src/main/java/com/somemore/community/usecase/board/CommunityBoardQueryUseCase.java
- src/test/java/com/somemore/community/controller/CommunityBoardQueryApiControllerTest.java
- src/test/java/com/somemore/community/repository/CommunityBoardRepositoryTest.java
- src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java
- src/test/java/com/somemore/community/service/board/DeleteCommunityBoardServiceTest.java
- resolved : #242 
- 커뮤니티 검색 조회 RDB 구현
- 커뮤니티 전체 조회 수정(검색 조회와 동일한 service 메서드 사용)
> Feature/242 커뮤니티 게시글 검색 조회 (RDB)

- build.gradle
- src/main/java/com/somemore/global/aspect/LoggingAspect.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- #252  
앱의 메트릭 데이터 수집을 위한 프로메테우스 연동 설정의 추가와
이어서 작업할 로깅을 위한 Logback, 로깅 aop 클래스의 추가 입니다.
- 메트릭 데이터 수집을 위한 프로메테우스 의존성 추가
- 관련 actuator 엔드포인트 설정을 yml에 추가
- log 기록을 위한 logback.xml 추가
- aop를 이용한 로그 기록을 위해 loggingAspect 클래스 추가
> Feature/252 프로메테우스 의존성 추가

- src/main/java/com/somemore/domains/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/somemore/domains/review/service/CreateReviewService.java
- src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryService.java
- src/main/java/com/somemore/global/exception/DuplicateException.java
- src/main/java/com/somemore/global/exception/handler/GlobalExceptionHandler.java
- src/test/java/com/somemore/domains/center/controller/CenterProfileCommandApiControllerTest.java
- src/test/java/com/somemore/domains/center/controller/CenterQueryApiControllerTest.java
- src/test/java/com/somemore/domains/center/controller/PreferItemCommandApiControllerTest.java
- src/test/java/com/somemore/domains/community/controller/CommunityBoardCommandApiControllerTest.java
- src/test/java/com/somemore/domains/community/controller/CommunityBoardQueryApiControllerTest.java
- src/test/java/com/somemore/domains/community/controller/CommunityCommentCommandApiControllerTest.java
- src/test/java/com/somemore/domains/community/controller/CommunityCommentQueryApiControllerTest.java
- src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
- src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
- src/test/java/com/somemore/domains/review/controller/ReviewCommandApiControllerTest.java
- src/test/java/com/somemore/domains/review/service/CreateReviewServiceTest.java
- src/test/java/com/somemore/domains/volunteer/controller/VolunteerProfileCommandControllerTest.java
- src/test/java/com/somemore/domains/volunteerapply/controller/CenterVolunteerApplyCommandApiControllerTest.java
- src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyCommandApiControllerTest.java
- src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
- src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryServiceTest.java
- src/test/java/com/somemore/support/ControllerTestSupport.java
resolved :
- #253 
리뷰 생성 및 컨트롤러 테스트 리팩토링
-  리뷰 생성 리팩토링
- 컨트롤러 테스트 리팩토링
- globalExceptionHandler 일부 리팩토링
- @Valid 유효성 실패시, meassge에 적용한 값이 출력되도록 변경했습니다.
-  여러개 필드에서 유효성 실패시 우선 검사되어 실패한 메세지가 출력되도록 수정
- 컨트롤러 테스트시 항상 print()를 출력하도록 변경하고 한글 깨짐이 발생하지 않도록 수정
위 두 개가 중점적이긴한데 이거에 대해 괜찮은지 의견 부탁드릴게요
> [REFACTOR] 리뷰 생성 및 컨트롤러 테스트 리팩토링

- src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiController.java
- src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
resolved : 
- #259 
봉사 지원 조회시 조회 내역이 없으면 210이 아닌 400 에러 발생 해결
> [BUG] 봉사 지원 조회

- src/main/java/com/somemore/domains/review/controller/ReviewCommandApiController.java
- src/main/java/com/somemore/domains/review/controller/ReviewQueryApiController.java
- src/main/java/com/somemore/domains/review/domain/Review.java
- src/main/java/com/somemore/domains/review/dto/request/ReviewCreateRequestDto.java
- src/main/java/com/somemore/domains/review/dto/request/ReviewUpdateRequestDto.java
- src/main/java/com/somemore/domains/review/dto/response/ReviewDetailResponseDto.java
- src/main/java/com/somemore/domains/review/dto/response/ReviewDetailWithNicknameResponseDto.java
- src/main/java/com/somemore/domains/review/service/CreateReviewService.java
- src/main/java/com/somemore/domains/review/service/DeleteReviewService.java
- src/main/java/com/somemore/domains/review/service/ReviewQueryService.java
- src/main/java/com/somemore/domains/review/service/UpdateReviewService.java
- src/main/java/com/somemore/domains/review/service/validator/ReviewValidator.java
- src/main/java/com/somemore/domains/review/usecase/DeleteReviewUseCase.java
- src/main/java/com/somemore/domains/review/usecase/ReviewQueryUseCase.java
- src/main/java/com/somemore/domains/review/usecase/UpdateReviewUseCase.java
- src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryService.java
- src/main/java/com/somemore/domains/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
- src/test/java/com/somemore/domains/review/controller/ReviewCommandApiControllerTest.java
- src/test/java/com/somemore/domains/review/domain/ReviewTest.java
- src/test/java/com/somemore/domains/review/service/CreateReviewServiceTest.java
- src/test/java/com/somemore/domains/review/service/DeleteReviewServiceTest.java
- src/test/java/com/somemore/domains/review/service/ReviewQueryServiceTest.java
- src/test/java/com/somemore/domains/review/service/UpdateReviewServiceTest.java
- src/test/java/com/somemore/domains/review/service/validator/ReviewValidatorTest.java
- src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryServiceTest.java
resolved : 
- #257 
- 리뷰 삭제
- 리뷰 수정
- 리팩토링
리뷰 삭제 기능
리뷰 수정 기능
- 내용 수정
- 이미지 수정(별도)
리뷰 도메인 리팩토링
- ReviewQueryUseCase 에 의존하도록 변경 (기존 ReviewRepository)
- `ReviewValidator` 도입
- 두군데 이상에서 사용되는 검증 메서드 추출해서 넣었습니다.
- 한군데에서만 사용되는 검증 메서드들은 추출하지 않음.
> [FEATURE] 리뷰 수정 및 삭제

- src/main/java/com/somemore/global/aspect/log/utils/SensitiveDataMasker.java
- #284  
컴파일시 발생하는 unchecked or unsafe operations 경고 해결을 위한
LoggingAspect의 수정
- TypeReference를 이용하여 런타임에도 타입정보를 명시적으로 인식할 수 있도록 수정
- 일부 메서드의 스타일 수정
> Fix/284 컴파일시 발생하는 type unchecked 경고 해결

- src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiController.java
- src/main/java/com/somemore/domains/volunteerapply/dto/response/VolunteerApplyWithReviewStatusResponseDto.java
- src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeService.java
- src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryService.java
- src/main/java/com/somemore/domains/volunteerapply/usecase/VolunteerApplyQueryFacadeUseCase.java
- src/main/java/com/somemore/domains/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
- src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
- src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeServiceTest.java
- src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryServiceTest.java
resolved : 
- #279 
특정 모집글에 대한 봉사자 지원 조회시 작성 리뷰 여부 필드 추가
> [FEATURE] 특정 모집글 봉사자 지원 조회 필드 추가

- src/main/java/com/somemore/global/auth/controller/SignController.java
- src/main/java/com/somemore/global/auth/idpw/filter/IdPwAuthFilter.java
- src/main/java/com/somemore/user/domain/UserRole.java
resolved : 
- #289  
유저 권한 관련 로직 문제가 있었습니다. 자연스럽게 수정해봤습니다.
1. 과제 관련 주요 수정
2. sign 관련 엔드포인트 수정
> [Fix] 유저 권한 관련 문제 해결, ID/PW sign 엔드 포인트 수정

- src/main/java/com/somemore/domains/center/domain/Center.java
- src/main/java/com/somemore/domains/community/domain/CommunityBoard.java
- src/main/java/com/somemore/domains/community/domain/CommunityComment.java
- src/main/java/com/somemore/domains/note/domain/Note.java
- src/main/java/com/somemore/domains/recruitboard/domain/RecruitBoard.java
- src/main/java/com/somemore/domains/review/domain/Review.java
- src/main/java/com/somemore/domains/volunteer/domain/Volunteer.java
- src/main/resources/application.yml
resolved : 
- #300 
> 엔티티 클래스에서 @Lob 붙은 컬럼에 대한 에러 수정
> ddl-auto validate로 변경
- @Lob 붙은 어노테이션들 @Cloumn(length)로 길이 변경 해주었습니다. 임시, 더 필요한 경우 바꿔주셔도 됩니다.
- 기관 봉사자 자기소개 500자, 쪽지 500자
- 커뮤니티, 모집글, 리뷰 1000자
- 커뮤니티 댓글 200자
- [ddl-auto 변경 이유](https://velog.io/@kevin_/%EB%82%B4%EA%B0%80-ddl-auto%EB%A5%BC-update%EB%A1%9C-%ED%96%88%EB%8D%98-%EC%9D%B4%EC%9C%A0%EC%99%80-%ED%8C%A8%EC%B0%A9)
- 이거 괜찮을지 코멘트 주시면 감사하겠습니다.
- 운영 DB 스키마 최신화하는 것은 PR전에 하면 충분하다고 생각해서 PR 직전에 update로 바꿔서 최신화해줘도 될 것 같아요.(다시 validate로 변경 후 PR)
> [FIX] @Lob 사용시 DB에 tinytext 저장되는 문제 해결

- src/main/resources/application.yml
- src/test/resources/application-test.yml
resolved : 
- #298 
> jpa open in view를 false로 변경
[open-in-view에 관한 이야기](https://medium.com/frientrip/spring-boot%EC%9D%98-open-in-view-%EA%B7%B8-%EC%9C%84%ED%97%98%EC%84%B1%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC-83483a03e5dc)
> [FIX] jpa open in view

- build.gradle
- src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiController.java
- src/main/java/com/somemore/domains/recruitboard/domain/RecruitBoard.java
- src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
- src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
- src/main/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepository.java
- src/main/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImpl.java
- src/main/java/com/somemore/domains/recruitboard/scheduler/RecruitBoardStatusUpdateScheduler.java
- src/main/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardService.java
- src/main/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidator.java
- src/main/java/com/somemore/domains/recruitboard/usecase/UpdateRecruitBoardUseCase.java
- src/main/java/com/somemore/domains/volunteerapply/service/ApplyVolunteerApplyService.java
- src/main/java/com/somemore/global/config/TimeConfig.java
- src/main/java/com/somemore/global/exception/ExceptionMessage.java
- src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
- src/test/java/com/somemore/domains/recruitboard/domain/RecruitBoardTest.java
- src/test/java/com/somemore/domains/recruitboard/domain/RecruitmentInfoTest.java
- src/test/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImplTest.java
- src/test/java/com/somemore/domains/recruitboard/scheduler/RecruitBoardStatusUpdateSchedulerTest.java
- src/test/java/com/somemore/domains/recruitboard/service/DeleteRecruitBoardServiceTest.java
- src/test/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryServiceTest.java
- src/test/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardServiceTest.java
- src/test/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidatorTest.java
- src/test/java/com/somemore/support/fixture/RecruitBoardFixture.java
resolved:
- #198
> 모집글 리팩토링
> 모집글 스케쥴링 기능
- RecruitStatus 생성자 추가
- RecruitBoardCreateRequestDto 에서 RECRUTING 상태로 생성하도록 변경
- 모집글 수정시 시간을 기준으로 수정 가능여부 검증
-  봉사 시작 일시 전날까지만 변경 가능하도록
- 모집글 수정시, 봉사 시작/종료 일시(변경이 없더라도)는 생성일 기준으로 검증하도록 수정
> [FEATURE] 모집글 스케쥴링

- src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiController.java
- src/main/java/com/somemore/domains/recruitboard/domain/RecruitBoard.java
- src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
- src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardDetailResponseDto.java
- src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardResponseDto.java
- src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardWithCenterResponseDto.java
- src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardWithLocationResponseDto.java
- src/main/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImpl.java
- src/main/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardService.java
- src/main/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryService.java
- src/main/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardService.java
- src/main/java/com/somemore/domains/recruitboard/usecase/CreateRecruitBoardUseCase.java
- src/main/java/com/somemore/domains/recruitboard/usecase/UpdateRecruitBoardUseCase.java
- src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
- src/test/java/com/somemore/domains/recruitboard/domain/RecruitBoardTest.java
- src/test/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImplTest.java
- src/test/java/com/somemore/domains/recruitboard/scheduler/RecruitBoardStatusUpdateSchedulerTest.java
- src/test/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardServiceTest.java
- src/test/java/com/somemore/domains/recruitboard/service/DeleteRecruitBoardServiceTest.java
- src/test/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryServiceTest.java
- src/test/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardServiceTest.java
- src/test/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidatorTest.java
- src/test/java/com/somemore/support/annotation/MockUser.java
- src/test/java/com/somemore/support/annotation/MockUserSecurityContextFactory.java
- src/test/java/com/somemore/support/fixture/RecruitBoardFixture.java
resolved : 
- #312 
NewCenter, UserCommonAttribute 추가에 따른 모집글 리팩토링
- @UserId, @RoleId 테스트를 위한 @MockUser 추가
- CurrentUser -> RoleId 변경
- 모집글 도메인에서 이미지 관련 로직 삭제
- Center 관련 로직 NewCenter 의존
나중에 시간이 되면 조인말고 객체로 풀겠습니다.
> [REFACTOR] 테이블 수정에 따른 모집글 리팩토링

- src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiController.java
- src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardResponseDto.java
- src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
resolved : 
- #324 
모집글 본인(기관)이 작성한 게시글 조회 기능 추가
- 모집글 본인(기관)이 작성한 게시글 조회 기능 추가
> [FEATURE] 모집글 본인이 작성한 게시글 조회 기능 추가

- src/main/java/com/somemore/global/imageupload/service/ImageUploadService.java
- src/main/java/com/somemore/global/imageupload/usecase/ImageUploadUseCase.java
- src/main/java/com/somemore/global/imageupload/util/ImageUploadUtils.java
- src/main/java/com/somemore/global/imageupload/validator/DefaultImageUploadValidator.java
- src/main/java/com/somemore/global/imageupload/validator/ImageUploadValidator.java
- src/test/java/com/somemore/global/imageupload/service/ImageUploadServiceTest.java
- src/test/java/com/somemore/global/imageupload/validator/DefaultImageUploadValidatorTest.java
- #288  
presigned 이미지 업로드 방식 구현과 그에 따른 테스트 추가, 코드 리팩토링 입니다
- presigned 이미지 업로드 방식 구현
- 파일 네임 검증 메서드 추가
- 일부 코드 리팩토링
> Feature/288 presigned 이미지 업로드 방식 구현

- src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiController.java
- src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
resolved : 
- #329 
로그인한 상태에서 API 요청으로 변경
- /api/volunteer-apply/recruit-board/{recruit_board_id}
> [FIX] 봉사자 특정 모집글 지원 상태 조회 API 수정

- src/main/java/com/somemore/global/auth/oauth/processor/OAuthUserProcessorImpl.java
- src/main/java/com/somemore/global/auth/sign/up/SignUpController.java
- src/main/java/com/somemore/global/auth/sign/up/SignUpService.java
- src/main/java/com/somemore/global/auth/sign/up/SignUpUseCase.java
resolved : 
- #331 
OAuth 로그인 중, 신규 유저의 봉사자 등록 로직 추가
OAuth 로그인 중, 신규 유저의 봉사자 등록 로직 추가
기존 로그인, 회원가입 로직 개선
> [FEATURE] OAuth 로그인 중, 신규 유저의 봉사자 등록 로직 추가

- src/main/java/com/somemore/user/controller/UserQueryController.java
- src/main/java/com/somemore/user/service/ValidateBasicInfoService.java
resolved : 
- #262 
유저 기본 정보 입력 상태 확인 API 추가
유저 기본 정보 입력 상태 확인 API 추가
> [FEAT] 유저 기본 정보 입력 상태 확인 API 추가

- src/main/java/com/somemore/domains/volunteerrecord/repository/VolunteerRankingRedisRepository.java
- src/main/java/com/somemore/global/redis/config/RedisConfig.java
- src/test/java/com/somemore/domains/volunteerrecord/service/GetVolunteerRankingServiceTest.java
- src/test/java/com/somemore/domains/volunteerrecord/service/RankingCacheServiceTest.java
- redis 레포지토리에 직렬화 로직 추가
- 테스트및 검증완료
- #327 
랭킹 조회시 발생하는 500번 에러 수정
Json 직렬화 문제로 인한 에러로 Redis 레포지토리 내부에 역직렬화 로직 추가
> fix/327 랭킹 json 직렬화 문제 해결

- src/main/java/com/somemore/domains/review/controller/ReviewCommandApiController.java
- src/main/java/com/somemore/domains/review/domain/Review.java
- src/main/java/com/somemore/domains/review/dto/request/ReviewCreateRequestDto.java
- src/main/java/com/somemore/domains/review/dto/response/ReviewDetailResponseDto.java
- src/main/java/com/somemore/domains/review/dto/response/ReviewDetailWithNicknameResponseDto.java
- src/main/java/com/somemore/domains/review/service/CreateReviewService.java
- src/main/java/com/somemore/domains/review/service/UpdateReviewService.java
- src/main/java/com/somemore/domains/review/usecase/CreateReviewUseCase.java
- src/main/java/com/somemore/domains/review/usecase/UpdateReviewUseCase.java
- src/test/java/com/somemore/domains/review/controller/ReviewCommandApiControllerTest.java
- src/test/java/com/somemore/domains/review/domain/ReviewTest.java
- src/test/java/com/somemore/domains/review/repository/ReviewRepositoryImplTest.java
- src/test/java/com/somemore/domains/review/service/CreateReviewServiceTest.java
- src/test/java/com/somemore/domains/review/service/DeleteReviewServiceTest.java
- src/test/java/com/somemore/domains/review/service/ReviewQueryServiceTest.java
- src/test/java/com/somemore/domains/review/service/UpdateReviewServiceTest.java
- src/test/java/com/somemore/domains/review/service/validator/ReviewValidatorTest.java
- src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeServiceTest.java
resolved : 
- #328 
리뷰 커맨드 기능 리팩토링
- RoleId로 변경
- 이미지 로직 관련 제거
> [REFACTOR] 리뷰 커맨드 기능 리팩토링

- src/main/java/com/somemore/center/controller/CenterQueryApiController.java
- src/main/java/com/somemore/center/dto/response/CenterProfileResponseDto.java
- src/main/java/com/somemore/center/repository/NEWCenterRepository.java
- src/main/java/com/somemore/center/repository/NEWCenterRepositoryImpl.java
- src/main/java/com/somemore/center/repository/record/CenterProfileDto.java
- src/main/java/com/somemore/center/service/NEWCenterQueryService.java
- src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
- src/main/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepository.java
- src/main/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepositoryImpl.java
- src/main/java/com/somemore/user/repository/usercommonattribute/record/UserProfileDto.java
- src/main/java/com/somemore/user/service/UserQueryService.java
- src/main/java/com/somemore/user/usecase/UserQueryUseCase.java
- src/test/java/com/somemore/center/controller/CenterQueryApiControllerTest.java
- src/test/java/com/somemore/center/repository/NEWCenterRepositoryImplTest.java
- src/test/java/com/somemore/center/service/NEWCenterQueryServiceTest.java
- src/test/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepositoryImplTest.java
- src/test/java/com/somemore/user/service/UserQueryServiceTest.java
- #320  
기관 프로필 조회 기능 리팩토링입니다.
- 유저 공통 속성에 프로필 조회를 위한 유스케이스 생성
- 새로운 기관 도메인에 프로필 조회 유스케이스 생성
- 컨트롤러를 새로운 도메인 디렉토리로 이전및 구 버전 테스트 코드 삭제
> Refactor/320 기관 프로필 조회 리팩토링

- src/main/java/com/somemore/center/domain/NEWCenter.java
- src/main/java/com/somemore/user/controller/UserCommandController.java
- src/main/java/com/somemore/user/controller/UserQueryController.java
- src/main/java/com/somemore/user/domain/UserCommonAttribute.java
- src/main/java/com/somemore/user/dto/basicinfo/CenterBasicInfoRequestDto.java
- src/main/java/com/somemore/user/dto/basicinfo/CommonBasicInfoRequestDto.java
- src/main/java/com/somemore/user/dto/basicinfo/VolunteerBasicInfoRequestDto.java
- src/main/java/com/somemore/user/service/UpdateBasicInfoService.java
- src/main/java/com/somemore/user/usecase/UpdateBasicInfoUseCase.java
- src/main/java/com/somemore/volunteer/domain/NEWVolunteer.java
- src/test/java/com/somemore/user/service/UpdateBasicInfoServiceTest.java
- src/test/java/com/somemore/user/service/ValidateBasicInfoServiceTest.java
resolved :
- #313 
유저의 프로필 업데이트 기능 추가
이는 유저의 회원가입 이후 초기 정보 입력에서도 사용 가능
유저의 프로필 업데이트 기능 추가
> [FEATURE] 유저 프로필(기본정보) 수정

- src/main/java/com/somemore/domains/review/controller/ReviewQueryApiController.java
- src/main/java/com/somemore/domains/review/dto/response/ReviewDetailResponseDto.java
- src/main/java/com/somemore/domains/review/dto/response/ReviewDetailWithNicknameResponseDto.java
- src/main/java/com/somemore/domains/review/service/ReviewQueryService.java
- src/main/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepository.java
- src/main/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepositoryImpl.java
- src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryService.java
- src/main/java/com/somemore/domains/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
- src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepository.java
- src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImpl.java
- src/main/java/com/somemore/volunteer/service/NEWVolunteerQueryService.java
- src/main/java/com/somemore/volunteer/usecase/NEWVolunteerQueryUseCase.java
- src/test/java/com/somemore/domains/review/service/ReviewQueryServiceTest.java
- src/test/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepositoryImplTest.java
- src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryServiceTest.java
- src/test/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImplTest.java
- src/test/java/com/somemore/volunteer/service/NEWVolunteerQueryServiceTest.java
resolved : 
- #349 
리뷰 조회 리팩토링
- 리뷰 상세 조회시 모집글 아이디 필드 추가
- 기존 리뷰 조회시 봉사자 닉네임 관련 리팩토링
- 로그인한 봉사자, 기관 리뷰 리스트 조회 API 추가
- 마이페이지에서 아마 봉사자랑 기관 아이디를 추출 못해서 API 엔드포인트 추가해놨습니다.
> [REFACTOR] 리뷰 조회 리팩토링

- src/main/java/com/somemore/center/controller/CenterCommandApiController.java
- src/main/java/com/somemore/center/dto/request/CenterProfileImgUpdateRequestDto.java
- src/main/java/com/somemore/center/service/UpdateCenterProfileImgService.java
- src/main/java/com/somemore/center/usecase/UpdateCenterProfileImgUseCase.java
- src/main/java/com/somemore/domains/center/controller/PreferItemCommandApiController.java
- src/main/java/com/somemore/user/domain/UserCommonAttribute.java
- src/main/java/com/somemore/user/dto/request/UpdateProfileImgUrlRequestDto.java
- src/main/java/com/somemore/user/service/UpdateProfileImgUrlService.java
- src/main/java/com/somemore/user/usecase/UpdateProfileImgUrlUseCase.java
- src/test/java/com/somemore/center/controller/CenterCommandApiControllerTest.java
- src/test/java/com/somemore/center/service/UpdateCenterProfileImgServiceTest.java
- src/test/java/com/somemore/domains/center/controller/PreferItemCommandApiControllerTest.java
- src/test/java/com/somemore/user/service/UpdateProfileImgUrlServiceTest.java
- #339  
이미지 업로드 방식이 presigned 방식으로 변경됨에 따라
기관 프로필 이미지 업데이트 api를 리팩토링했습니다.
프론트에서의 에러가 우려되어 기존 이용하던 기능은 그대로 두었습니다.
- 유저 공통속성 엔티티에 imgUrl 상태 변경 메서드 추가
- 유저 공통속성의 프로필 이미지 url 변경 유스케이스 생성
- 기관 도메인에 프로필 이미지 업데이트 유스케이스 구현
- 기관 프로필 이미지 업데이트 엔드포인트 추가
> Refactor/339 기관 프로필 이미지 업데이트 리팩토링

- src/main/java/com/somemore/center/repository/NEWCenterRepository.java
- src/main/java/com/somemore/center/repository/NEWCenterRepositoryImpl.java
- src/main/java/com/somemore/center/repository/record/CenterOverviewInfo.java
- src/main/java/com/somemore/center/service/NEWCenterQueryService.java
- src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
- src/main/java/com/somemore/domains/center/repository/center/CenterRepository.java
- src/main/java/com/somemore/domains/center/repository/center/CenterRepositoryImpl.java
- src/main/java/com/somemore/domains/center/service/query/CenterQueryService.java
- src/main/java/com/somemore/domains/center/usecase/query/CenterQueryUseCase.java
- src/main/java/com/somemore/domains/interestcenter/controller/InterestCenterCommandApiController.java
- src/main/java/com/somemore/domains/interestcenter/controller/InterestCenterQueryApiController.java
- src/main/java/com/somemore/domains/interestcenter/dto/response/InterestCentersResponseDto.java
- src/main/java/com/somemore/domains/interestcenter/service/CancelInterestCenterService.java
- src/main/java/com/somemore/domains/interestcenter/service/InterestCenterQueryService.java
- src/main/java/com/somemore/domains/interestcenter/service/RegisterInterestCenterService.java
- src/test/java/com/somemore/center/repository/NEWCenterRepositoryImplTest.java
- src/test/java/com/somemore/center/service/NEWCenterQueryServiceTest.java
- src/test/java/com/somemore/domains/center/service/query/CenterQueryServiceTest.java
- src/test/java/com/somemore/domains/interestcenter/controller/InterestCenterCommandApiControllerTest.java
- src/test/java/com/somemore/domains/interestcenter/controller/InterestCenterQueryApiControllerTest.java
- src/test/java/com/somemore/domains/interestcenter/service/CancelInterestCenterServiceTest.java
- src/test/java/com/somemore/domains/interestcenter/service/InterestCenterQueryServiceTest.java
- src/test/java/com/somemore/domains/interestcenter/service/RegisterInterestCenterServiceTest.java
resolved :
- #356 
관심 기관 리팩토링
- 관심 기관 추가/제거
- 관심 기관 조회
> [REFACTOR] 관심 기관 리팩토링

- src/main/java/com/somemore/domains/note/controller/NoteCommandApiController.java
- src/main/java/com/somemore/domains/note/controller/NoteQueryApiController.java
- src/main/java/com/somemore/domains/note/repository/NoteRepositoryImpl.java
- src/main/java/com/somemore/domains/note/service/NoteMarkAsReadService.java
- src/main/java/com/somemore/domains/note/service/SendNoteToCenterService.java
- src/main/java/com/somemore/domains/note/service/SendNoteToVolunteerService.java
- src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepository.java
- src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImpl.java
- src/main/java/com/somemore/volunteer/service/NEWVolunteerQueryService.java
- src/main/java/com/somemore/volunteer/usecase/NEWVolunteerQueryUseCase.java
- src/test/java/com/somemore/domains/note/controller/NoteCommandApiControllerTest.java
- src/test/java/com/somemore/domains/note/controller/NoteQueryApiControllerTest.java
- src/test/java/com/somemore/domains/note/repository/NoteRepositoryImplTest.java
- src/test/java/com/somemore/domains/note/service/NoteQueryServiceTest.java
- src/test/java/com/somemore/domains/note/service/SendNoteToCenterServiceTest.java
- src/test/java/com/somemore/domains/note/service/SendNoteToVolunteerServiceTest.java
- src/test/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImplTest.java
- src/test/java/com/somemore/volunteer/service/NEWVolunteerQueryServiceTest.java
resolved : 
- #365 
- 쪽지 리팩토링
- 쪽지 커맨드 기능 리팩토링
- 쪽지 조회 기능 리팩토링
> [REFACTOR] 쪽지 리팩토링

- src/main/java/com/somemore/center/service/NEWCenterQueryService.java
- src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
- src/main/java/com/somemore/domains/community/event/CommentAddedEvent.java
- src/main/java/com/somemore/domains/community/service/comment/CreateCommunityCommentService.java
- src/main/java/com/somemore/domains/interestcenter/event/domain/InterestCenterCreateRecruitBoardEvent.java
- src/main/java/com/somemore/domains/interestcenter/event/handler/CreateRecruitBoardHandlerImpl.java
- src/main/java/com/somemore/domains/notification/controller/NotificationQueryController.java
- src/main/java/com/somemore/domains/notification/event/converter/NotificationMessageConverter.java
- src/main/java/com/somemore/domains/recruitboard/event/CreateRecruitBoardEvent.java
- src/main/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardService.java
- src/main/java/com/somemore/domains/volunteerapply/event/VolunteerApplyEvent.java
- src/main/java/com/somemore/domains/volunteerapply/event/VolunteerApplyStatusChangeEvent.java
- src/main/java/com/somemore/domains/volunteerapply/event/VolunteerReviewRequestEvent.java
- src/main/java/com/somemore/domains/volunteerapply/service/ApplyVolunteerApplyService.java
- src/main/java/com/somemore/domains/volunteerapply/service/SettleVolunteerApplyFacadeService.java
- src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyStatusChangeService.java
- src/main/java/com/somemore/domains/volunteerrecord/event/VolunteerRecordCreateEvent.java
- src/main/java/com/somemore/domains/volunteerrecord/event/VolunteerRecordEventPublisher.java
- src/main/java/com/somemore/global/auth/annotation/UserIdArgumentResolver.java
- src/test/java/com/somemore/domains/interestcenter/handler/CreateRecruitBoardHandlerImplTest.java
- src/test/java/com/somemore/domains/notification/converter/NotificationMessageConverterTest.java
- src/test/java/com/somemore/domains/notification/handler/NotificationHandlerTest.java
resolved : 
- #355 
유저 테이블 변경에 따른 알림 로직 변경 및 개선
유저 테이블 변경에 따른 알림 로직 변경 및 개선
- 이벤트 생성 방식
- 테스트 수정
> [REFACTOR] 유저 테이블 변경에 따른 알림 로직 변경 및 개선

- src/main/java/com/somemore/domains/community/controller/CommunityBoardCommandApiController.java
- src/main/java/com/somemore/domains/community/controller/CommunityCommentCommandApiController.java
- src/main/java/com/somemore/domains/community/domain/CommunityBoard.java
- src/main/java/com/somemore/domains/community/dto/request/CommunityBoardCreateRequestDto.java
- src/main/java/com/somemore/domains/community/dto/response/CommunityBoardDetailResponseDto.java
- src/main/java/com/somemore/domains/community/dto/response/CommunityCommentResponseDto.java
- src/main/java/com/somemore/domains/community/repository/board/CommunityBoardRepositoryImpl.java
- src/main/java/com/somemore/domains/community/repository/comment/CommunityCommentRepositoryImpl.java
- src/main/java/com/somemore/domains/community/service/board/CreateCommunityBoardService.java
- src/main/java/com/somemore/domains/community/service/board/UpdateCommunityBoardService.java
- src/main/java/com/somemore/domains/community/usecase/board/CreateCommunityBoardUseCase.java
- src/main/java/com/somemore/domains/community/usecase/board/UpdateCommunityBoardUseCase.java
- src/test/java/com/somemore/domains/community/controller/CommunityBoardCommandApiControllerTest.java
- src/test/java/com/somemore/domains/community/controller/CommunityCommentCommandApiControllerTest.java
- src/test/java/com/somemore/domains/community/repository/CommunityBoardRepositoryTest.java
- src/test/java/com/somemore/domains/community/repository/CommunityCommentRepositoryTest.java
- src/test/java/com/somemore/domains/community/service/board/CommunityBoardQueryServiceTest.java
- src/test/java/com/somemore/domains/community/service/board/CreateCommunityBoardServiceTest.java
- src/test/java/com/somemore/domains/community/service/board/DeleteCommunityBoardServiceTest.java
- src/test/java/com/somemore/domains/community/service/board/UpdateCommunityBoardServiceTest.java
- src/test/java/com/somemore/domains/community/service/comment/CommunityCommentQueryServiceTest.java
- src/test/java/com/somemore/domains/community/service/comment/CreateCommunityCommentServiceTest.java
- src/test/java/com/somemore/domains/community/service/comment/DeleteCommunityCommentServiceTest.java
- src/test/java/com/somemore/domains/community/service/comment/UpdateCommunityCommentServiceTest.java
- src/test/java/com/somemore/support/fixture/CommunityBoardFixture.java
- resolved : #307 
- 커뮤니티 댓글 반환값에 작성자 ID 추가
- @CurrentUser -> @RoledId
- volunteer -> newVolunteer
- 이미지 링크 삭제
> [REFACTOR] 커뮤니티 리팩토링

- src/main/java/com/somemore/global/imageupload/controller/GetPresignedUrlController.java
- src/main/java/com/somemore/user/controller/UserCommandController.java
resolved : 
- #368 
user secured 문제 해결
user secured 문제 해결
> [FIX] user secured 문제 해결

- src/main/java/com/somemore/global/auth/jwt/domain/TokenType.java
- src/main/java/com/somemore/user/controller/UserCommandController.java
resolved : 
- #371 
프로필 이미지 Presigned URL 반환
프로필 이미지 Presigned URL 반환
+ 액세스 토큰 만료 기한 정상화
> [FIX] 프로필 이미지 Presigned URL 반환
