prgrms-web-devcourse-final-project/WEB1_1_Bongdari_BE

build.gradle
- 테스트 커버리지 제외 관련 설정 추가
resolved : #31  
테스트 커버리지 제외 설정을 위한 sonar propertie 추가
=> Fix: sonar propertie 추가

.github/workflows/CD.yml
- CD.yml에 빌드를 위한 환경변수 추가
resolved : #31  
누락된 CD.yml 환경변수 추가
CD.yml에 누락된 빌드를 위한 환경변수 추가 수정입니다.
=> fix: add env to CD.yml

.github/workflows/CD.yml, .github/workflows/CI.yml
컨트롤러 테스트를 위한 임시 토큰 발급 기능 관련 환경변수 추가 업데이트입니다.
- swagger에서의 테스트를 위한 환경변수 추가
=> CICD/ workflow 환경변수 추가

src/main/java/com/somemore/auth/util/DevAccountSetUpConfig.java
resolved :
- #93 
- DevAccountSetUpConfig 클래스 오타 수정
=> hotfix: fix typo

src/main/java/com/somemore/global/configure/SecurityConfig.java, src/main/java/com/somemore/global/configure/WebConfig.java
resolved : 
- #111 
CORS 해결
로컬호스트, S3 주소를 허용했습니다.
잘못된 설정이 있다면 알려주세요!
=> Feature/111 CORS

src/main/java/com/somemore/auth/oauth/handler/failure/CustomOAuthFailureHandler.java, src/main/java/com/somemore/auth/signout/service/SignOutService.java, src/main/java/com/somemore/auth/signout/usecase/SignOutUseCase.java, src/main/java/com/somemore/center/controller/CenterSignController.java, src/main/java/com/somemore/global/configure/WebConfig.java, src/main/java/com/somemore/volunteer/controller/VolunteerSignController.java, src/test/java/com/somemore/volunteer/service/SignOutVolunteerServiceTest.java
resolved : 
- #110 
기관 로그아웃
기관 로그아웃, CORS 설정 추가
=> Feature/110 기관 로그아웃

src/main/java/com/somemore/global/configure/WebConfig.java
resolved : 
- #126 
프론트 배포 주소 변경으로 CORS 해결
allowOrigin 추가
=> Fix/ CORS 해결

build.gradle
- spring-boot-starter-actuator 추가
- #130  
무중단 배포시 이용하는 서버 헬스 체크를 위한 의존성 추가 입니다.
- build.gradle에 spring-boot-starter-actuator 의존성 추가
=> Feature: 서버 헬스 체크를 위한 의존성 추가

src/main/java/com/somemore/global/common/response/ApiResponse.java
resolved : 
- #134 
- Swagger API 명세에 data 부분이 출력되지 않는 문제 해결
=> Bug/135 스웨거 공통 응답 데이터 필드 수정

.github/workflows/CD.yml
- 새로운 서버로의 배포 테스트 커밋
resolved : #1
=> cicd: 배포테스트용 커밋

src/main/java/com/somemore/center/controller/CenterProfileCommandApiController.java, src/main/java/com/somemore/center/domain/Center.java, src/main/java/com/somemore/center/dto/request/CenterProfileUpdateRequestDto.java, src/main/java/com/somemore/center/service/command/UpdateCenterProfileService.java, src/main/java/com/somemore/center/usecase/command/UpdateCenterProfileUseCase.java, src/test/java/com/somemore/center/controller/CenterProfileCommandApiControllerTest.java, src/test/java/com/somemore/center/service/command/UpdateCenterProfileServiceTest.java
resolved : 
- #136
- 센터 프로필 수정 구현
=> Feature/136 기관 마이페이지 프로필 수정

.github/workflows/CD.yml
- #140  
무중단 배포 구현에 따른 cd workflow 수정
- 서버내에 무중단 배포 스크립트를 개발했습니다
- 기존 compose up 명령을 배포 스크립트 실행 명령으로 변경했습니다
=> CICD/140 무중단 배포 적용

src/main/java/com/somemore/global/configure/SwaggerConfig.java
resolved : 
- #146 
Swagger에서 http 요청으로 인한 CORS 에러
=> fix(swagger): Swagger에서 http 요청으로 인한 CORS 에러

src/main/java/com/somemore/develop/TokenGenerateMachine.java, src/main/java/com/somemore/develop/controller/TokenGenerateMachine.java
resolved : 
- #150 
개발용 토큰 발급
개발용 토큰 발급
내일(금요일 12/6) 삭제 예정
=> Feature/150 개발용 토큰 발급

src/main/java/com/somemore/global/configure/WebConfig.java
resolved : 
- #159 
CORS config PATCH method 추가
CORS config PATCH method
유진 님이 찾아주셨습니다.
=> feat(CORS): PATCH 메서드 추가

src/main/java/com/somemore/auth/cookie/CookieService.java
resolved : 
- #162 
서브 도메인 쿠키 공유를 설정했습니다.
- .domain()을 통해서 서브 도메인 명시
- samesite 설정 변경
정상 작동하면 좋겠습니다.
=> feat/162 서브 도메인 쿠키 공유

build.gradle, src/main/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeService.java, src/main/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeUseCase.java, src/main/java/com/somemore/global/exception/ExceptionMessage.java, src/main/java/com/somemore/global/redis/config/RedisConfig.java, src/main/java/com/somemore/volunteer/service/UpdateVolunteerLockService.java, src/main/java/com/somemore/volunteer/usecase/UpdateVolunteerUseCase.java, src/main/java/com/somemore/volunteerapply/controller/CenterVolunteerApplyCommandApiController.java, src/main/java/com/somemore/volunteerapply/dto/request/VolunteerApplySettleRequestDto.java, src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepository.java, src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImpl.java, src/main/java/com/somemore/volunteerapply/service/VolunteerApplyQueryService.java, src/main/java/com/somemore/volunteerapply/usecase/VolunteerApplyQueryUseCase.java, src/test/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeServiceTest.java, src/test/java/com/somemore/volunteer/domain/VolunteerTest.java, src/test/java/com/somemore/volunteer/service/UpdateVolunteerLockServiceTest.java, src/test/java/com/somemore/volunteerapply/controller/CenterVolunteerApplyCommandApiControllerTest.java, src/test/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImplTest.java, src/test/java/com/somemore/volunteerapply/service/VolunteerApplyQueryServiceTest.java
resolved :
- #148 
-  봉사 활동 후 정산하기
- 지원 상태가 참석으로 변경
- 봉사자의 봉사 시간이 해당 봉사의 시간만큼 증가
- 봉사자의 봉사 숫자 1 증가
=> Feature/148 봉사 활동 정산하기

src/main/java/com/somemore/global/common/entity/BaseEntity.java, src/main/java/com/somemore/note/controller/NoteQueryApiController.java, src/main/java/com/somemore/note/repository/NoteRepository.java, src/main/java/com/somemore/note/repository/NoteRepositoryImpl.java, src/main/java/com/somemore/note/repository/mapper/NoteReceiverViewForCenter.java, src/main/java/com/somemore/note/repository/mapper/NoteReceiverViewForVolunteer.java, src/main/java/com/somemore/note/service/NoteQueryService.java, src/main/java/com/somemore/note/usecase/NoteQueryUseCase.java, src/test/java/com/somemore/note/controller/NoteQueryApiControllerTest.java, src/test/java/com/somemore/note/repository/NoteRepositoryImplTest.java, src/test/java/com/somemore/note/service/NoteQueryServiceTest.java
- #156  
봉사자/기관의 자신에게 온 쪽지 목록을 확인하는 기능입니다.
- 데이터 조회를 위한 쿼리 메서드 구현
- 서비스 레이어 구현
- 응답 객체 생성
- 컨트롤러 구현
=> Feature/156 봉사자와 기관의 자신에게 온 쪽지 목록 

src/main/java/com/somemore/review/dto/response/ReviewResponseDto.java, src/test/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeServiceTest.java, src/test/java/com/somemore/volunteer/service/UpdateVolunteerLockServiceTest.java
resolved : 
- #194 
리뷰 응답 DTO 수정
=> BUG/194 리뷰 응답 DTO 수정

src/main/java/com/somemore/note/service/NoteMarkAsReadService.java, src/main/java/com/somemore/note/service/NoteQueryService.java
- #208  
- @Transactinal의 추가로 일부 메서드 쓰기 연산 허용
=> Big/208 쪽지 읽음처리 서비스 레이어 수정

src/main/java/com/somemore/review/dto/response/ReviewWithNicknameResponseDto.java, src/main/java/com/somemore/review/repository/ReviewRepositoryImpl.java
resolved : 
- #210 
리뷰 페이징 조회 오류 수정
- 카운트 쿼리쪽 문제였습니다.
=> HOTFIX/210 리뷰 페이징 조회 오류 수정

.github/workflows/CD.yml, .github/workflows/CI.yml
workflow 환경변수 추가 업데이트 입니다.
- Elasticsearch 관련 환경변수 추가
=> cicd: 환경변수 추가

src/main/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiController.java, src/test/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiControllerTest.java
- resolved : #227 
- 봉사활동 모집글 엔드포인트 prefix 수정
- 믿어주셨는데 실망을 안겨드리네요..
=> Fix/227 봉사활동 모집글 엔드포인트 prefix 수정

src/main/java/com/somemore/community/controller/CommunityBoardQueryApiController.java, src/main/java/com/somemore/community/domain/CommunityBoardDocument.java, src/main/java/com/somemore/community/repository/board/CommunityBoardDocumentRepository.java, src/main/java/com/somemore/community/repository/board/CommunityBoardRepository.java, src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java, src/main/java/com/somemore/community/scheduler/CommunityBoardUpdateScheduler.java, src/main/java/com/somemore/community/service/board/CommunityBoardDocumentService.java, src/main/java/com/somemore/community/usecase/board/CommunityBoardDocumentUseCase.java, src/main/java/com/somemore/global/configure/ElasticsearchConfig.java, src/main/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiController.java, src/main/java/com/somemore/recruitboard/domain/RecruitBoardDocument.java, src/main/java/com/somemore/recruitboard/repository/RecruitBoardDocumentRepository.java, src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepository.java, src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java, src/main/java/com/somemore/recruitboard/scheduler/RecruitBoardUpdateScheduler.java, src/main/java/com/somemore/recruitboard/service/query/RecruitBoardDocumentService.java, src/main/java/com/somemore/recruitboard/usecase/query/RecruitBoardDocumentUseCase.java, src/test/java/com/somemore/community/controller/CommunityBoardQueryApiControllerTest.java, src/test/java/com/somemore/community/repository/CommunityBoardDocumentRepositoryTest.java, src/test/java/com/somemore/community/repository/CommunityBoardRepositoryTest.java, src/test/java/com/somemore/community/scheduler/CommunityBoardUpdateSchedulerTest.java, src/test/java/com/somemore/community/service/board/CommunityBoardDocumentServiceTest.java, src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java, src/test/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiControllerTest.java, src/test/java/com/somemore/recruitboard/repository/RecruitBoardDocumentRepositoryTest.java, src/test/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImplTest.java, src/test/java/com/somemore/recruitboard/scheduler/RecruitBoardUpdateSchedulerTest.java, src/test/java/com/somemore/recruitboard/service/query/RecruitBoardDocumentServiceTest.java, src/test/java/com/somemore/recruitboard/service/query/RecruitBoardQueryServiceTest.java
- resolved : #233 
- elasticsearch 관련 코드 주석 처리
=> Refactor/233 elasticsearch 관련 코드 주석 처리

README.md
resolved : 
- #240  
리드미에 주요 기능을 기입하면서 다른 형식들도 조금 수정해봤습니다.
=> DOCS/240 README 업데이트

src/main/resources/application.yml
- #256  
블루 그린 배포중 health 체크 실패에 대한 엔드포인트 추가 수정입니다.
- spring actuator의 health check 엔드포인트 추가
=> Fix/ 헬스 체크 엔드포인트 추가

src/main/resources/logback-spring.xml
- #271  
앱 컨테이너와 loki의 연결 에러 수정을 위한 logback 수정
- logback-spring.xml 파일의 appender 수정
=> Fix/271 logback의 loki 관련 설정 수정

src/main/java/com/somemore/global/config/WebConfig.java
resolved : 
- #291  
액세스 토큰이 담긴 헤더에 프론트엔드가 접근할 수 있도록 설정합니다.
- expose Authorization header
- allow origin 수정
=> [FEATURE] Authorization header setting

.github/workflows/CD.yml, .github/workflows/CI.yml, src/main/java/com/somemore/domains/center/domain/Center.java, src/main/java/com/somemore/domains/center/domain/PreferItem.java, src/main/java/com/somemore/domains/volunteer/domain/Volunteer.java, src/main/java/com/somemore/domains/volunteer/domain/VolunteerDetail.java
resolved : 
- #304 
카카오 CICD 문제 해결
카카오 설정 추가
봉사자 테이블 명 롤백 (old 삭제)
기관, 선호 물품 테이블 명 표시
=> [CICD] 카카오 CICD 문제 해결

src/main/java/com/somemore/global/auth/jwt/controller/TokenExchangeController.java, src/main/java/com/somemore/global/auth/sign/out/SignOutController.java, src/main/java/com/somemore/global/sse/controller/SseController.java
resolved : #314  
CurrentUser 변경
CurrentUser 변경
=> [FIX] @CurrentUser를 @UserId로 변경

.github/workflows/CI.yml
resolved : 
- #342 
actions/upload-artifact: v3 -> v4
=> [FIX] git actions 버전 문제 해결

src/main/java/com/somemore/domains/notification/controller/NotificationCommandController.java, src/main/java/com/somemore/domains/notification/dto/NotificationResponseDto.java, src/main/java/com/somemore/domains/notification/repository/NotificationJpaRepository.java, src/main/java/com/somemore/domains/notification/repository/NotificationRepository.java, src/main/java/com/somemore/domains/notification/repository/NotificationRepositoryImpl.java, src/main/java/com/somemore/domains/notification/service/NotificationCommandService.java, src/main/java/com/somemore/domains/notification/service/NotificationQueryService.java, src/main/java/com/somemore/domains/notification/usecase/NotificationQueryUseCase.java, src/test/java/com/somemore/domains/notification/handler/NotificationHandlerTest.java, src/test/java/com/somemore/domains/notification/repository/NotificationRepositoryTest.java, src/test/java/com/somemore/domains/notification/service/NotificationCommandServiceTest.java
resolved : 
- #346 
유저 테이블에 알맞게 알림 로직 수정
유저 테이블에 알맞게 알림 로직 수정
이후에 모든 도메인의 알림 생성 부분을 변경할 예정입니다.
=> [REFACTOR] 유저 테이블에 알맞게 알림 로직 수정

src/main/java/com/somemore/global/auth/idpw/filter/IdPwAuthFilter.java, src/main/java/com/somemore/global/auth/jwt/domain/TokenType.java, src/main/java/com/somemore/global/config/SecurityConfig.java
resolved : 
- #353  
IDPW 로그인시 쿠키로 임시 토큰 발급
IDPW 로그인시 쿠키로 임시 토큰 발급
=> [FEATURE] IDPW 로그인시 쿠키로 임시 토큰 발급

src/main/java/com/somemore/global/auth/jwt/domain/TokenType.java, src/main/java/com/somemore/global/auth/jwt/filter/JwtAuthFilter.java
resolved : 
- #357  
액세스 토큰 쿠키 명명 수정으로 필터 로직 수정
액세스 토큰 쿠키 명명 수정으로 필터 로직 수정
=> [FIX] 액세스 토큰 쿠키 명명 수정으로 필터 로직 수정

src/main/java/com/somemore/user/dto/basicinfo/VolunteerBasicInfoRequestDto.java
resolved :
- #373 
유저 정보 업데이트 오류 수정
=> [FIX] 유저 정보 업데이트 오류 수정
